- name: Download Prometheus Node Exporter
  ansible.builtin.unarchive:
    src: "{{ exporter_url }}"
    dest: /opt
    remote_src: true

- name: Restart prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted