route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'web.hook'
receivers:
  - name: "email"
    email_configs:
      - to: srinikdevops0131@gmail.com      # you@example.com
        from: srinikdevops0131@gmail.com  # alertmanager@example.com
        smarthost: "email-smtp.us-east-1.amazonaws.com:587"
        auth_username: "{{AKIA5NLXHH55YT43R4UM}}"
        auth_password: "{{BObSPWIOrR1+mwUG6kEBFD5SzC/rfVzwawOwFKDaEuvt}}"
        require_tls: true
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']

