groups:
- name: roboshop-service-alerts
  rules:
  {% for component in components %}

  - alert: Service down alert -- {{ component.name }} Service
    expr: node_systemd_unit_state{exported_name="{{ component.service_name }}.service", state="active"}
        for: 30s
        labels:
          severity: critical
          appName: {{ component.name }}
        annotations:
          summary: Service Down on some server - Service Name -- {{ component.name }}.service
    {% endfor %}