groups:
  - name: roboshop-service-alerts
    rules:
      - alert: Service down
        expr: node_systemd_unit_state{exported_name="cart.service", state="active"}
        for: 30s
        labels:
          severity: critical
          appName: cart
        annotations:
          summary: Service Down on some server - Service Name -- cart.service